# Site settings
title: Dayboard Blog
email: support@dayboard.co
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "https://blog.dayboard.co" # the base hostname & protocol for your site
permalink: /:title
future: false
timezone: America/New_York

twitter_username: dayboardco
github_username:  jtcchan
facebook_username:  daybaordco

# Build settings
markdown: kramdown

author:
  jenn:
    name: "Jennifer Lo"
    display_name: "Jennifer"
    avatar_url: "/assets/images/avatars/jenn.jpg"
    bio: >
      Jennifer Lo is the co-founder and marketing lead at Dayboard. She's always down for an outdoor adventure, good company, and great wine.
    twitter: jennlo_
  john:
    name: "John Chan"
    display_name: "John"
    avatar_url: "/assets/images/avatars/john.jpg"
    bio: >
      John Chan is the co-founder and product lead at Dayboard. He often thinks out loud and is perfectly happy with having a conversion with himself. When he's not building Dayboard, he's likely binge playing video games.
    twitter: jtcchan
  abhi:
    name: "Abhi Vair"
    display_name: "Abhi"
    avatar_url: "/assets/images/avatars/abhi.jpg"
    bio: >
      Abhi Vair is a full stack developer at Dayboard. She's your classic nightowl, loves late night coffee runs and is always up for a adventure.
  # Guest Authors
  kat:
    name: "Kat Boogaard"
    display_name: "Kat"
    avatar_url: "/assets/images/avatars/kat.jpg"
    bio: >
      Kat is a Midwest-based freelance writer (writing this article for AND CO) who has a real passion for helping other freelancers grow their businesses. She has written for many publications including Forbes, Inc., Fast Company, Business Insider, Time, and Mashable.
    twitter: kat_boogaard

