# Site settings
title: Dayboard Blog
email: support@dayboard.co
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://blog.dayboard.co" # the base hostname & protocol for your site
twitter_username: dayboardco
github_username:  jtcchan
facebook_username:  daybaordco

# Build settings
markdown: kramdown

author:
  jenn:
    name: "Jennifer Lo"
    display_name: "Jennifer"
    avatar_url: "/blog/assets/images/avatars/jenn.jpg"
    bio: >
      She writes stuff.
    twitter: jennlo_
  john:
    name: "John Chan"
    display_name: "John"
    avatar_url: "/blog/assets/images/avatars/john.jpg"
    bio: >
      He's awesome.
    twitter: jtcchan