# Site settings
title: Dayboard Blog
email: support@dayboard.co
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://blog.dayboard.co" # the base hostname & protocol for your site
permalink: /:title

twitter_username: dayboardco
github_username:  jtcchan
facebook_username:  daybaordco

# Build settings
markdown: kramdown

author:
  jenn:
    name: "Jennifer Lo"
    display_name: "Jennifer"
    avatar_url: "/blog/assets/images/avatars/jenn.jpg"
    bio: >
      Jennifer Lo is the co-founder and marketing lead at Dayboard. She loves to experiment with new things and drink wine.
    twitter: jennlo_
  john:
    name: "John Chan"
    display_name: "John"
    avatar_url: "/blog/assets/images/avatars/john.jpg"
    bio: >
      John Chan is the co-founder and product lead at Dayboard. He loves to build cool stuff and binge play video games.
    twitter: jtcchan