# Site settings
title: The Dayboard Blog
email: support@dayboard.co
description: > # this means to ignore newlines until "baseurl:"
  Interested in productivity, remote work, mindfulness and attention management?
  Join the Dayboard team as we share our thoughts, tips and lessons learned on our blog.
url: "https://blog.dayboard.co" # the base hostname & protocol for your site
permalink: /:title
future: false
timezone: America/New_York

twitter_username: dayboardco
github_username:  jtcchan
facebook_username:  daybaordco

# Build settings
markdown: kramdown
